"""Add foreign key to Session and Bio

Revision ID: 25ef6d142c03
Revises: 3599de996267
Create Date: 2025-06-20 00:56:50.861229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ef6d142c03'
down_revision = '3599de996267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_bios_speaker_id_speakers'), 'bios', 'speakers', ['speaker_id'], ['id'])
    op.create_foreign_key(op.f('fk_sessions_event_id_events'), 'sessions', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_sessions_event_id_events'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('fk_bios_speaker_id_speakers'), 'bios', type_='foreignkey')
    # ### end Alembic commands ###
